version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo Retrieving authentication token and authenticating Docker client...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 024848451374.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=024848451374.dkr.ecr.ap-south-1.amazonaws.com/node-app
      - IMAGE_TAG=latest

  build:
    commands:
      - echo Building Docker image...
      - docker build -t node-app .

  post_build:
    commands:
      - echo Tagging the Docker image...
      - docker tag node-app:latest 024848451374.dkr.ecr.ap-south-1.amazonaws.com/node-app:latest
      - echo Pushing Docker image to ECR...
      - docker push 024848451374.dkr.ecr.ap-south-1.amazonaws.com/node-app:latest
      - echo Image pushed successfully!

artifacts:
  files:
    - Dockerfile
    - buildspec.yml
